#!/usr/bin/env python3
"""Generate a nose-cap .obj mesh: a simple pointy cone (stack axis +Z).

Part meshes are authored centered at the origin with the stack axis along
+Z. The unit cap is radius 1, height 0.5 (height = radius / 2): a base
disc at z = -h/2 and an apex at z = +h/2. Larger sizes come from
rescale_obj.py (sx = sy = r, sz = h / 2), e.g.

    python3 gen_nose_cap.py res/nose_cap.obj
    python3 rescale_obj.py res/nose_cap.obj res/nose_cap_r3h1.5.obj --sx 3 --sy 3 --sz 0.75
    python3 rescale_obj.py res/nose_cap.obj res/nose_cap_r5h2.5.obj --sx 5 --sy 5 --sz 1.25

Geometry: 32 side segments, a base disc fan, smooth analytic side normals,
flat normals on the base disc and apex. Winding is CCW from outside
(the renderer culls back faces). UVs: the side wraps u around the axis
(v = 0 at the base rim, 1 at the apex), the disc is planar -- the part's
texture is a flat fill, so they only need to be present (CalcTangentSpace
requires a UV channel).
"""

import argparse
import math


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--radius", type=float, default=1.0)
    ap.add_argument("--height", type=float, default=0.5,
                    help="cone height (default: radius / 2)")
    ap.add_argument("--segments", type=int, default=32)
    a = ap.parse_args()
    if a.radius <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("radius/height must be > 0, segments >= 3")

    r, h, n = a.radius, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    verts, uvts, norms, faces = [], [], [], []
    for i in range(n):
        th = 2.0 * math.pi * i / n
        ct, st = math.cos(th), math.sin(th)
        verts.append((r * ct, r * st, zbase))
        uvts.append((i / float(n), 0.0))
        # side normal: perpendicular to the side vector (apex -> base) in
        # the (radial, z) plane, pointing out and slightly toward the apex
        L = math.sqrt(h * h + r * r)
        norms.append((h * ct / L, h * st / L, r / L))
    # apex
    apex = len(verts)
    verts.append((0.0, 0.0, ztop))
    uvts.append((0.0, 1.0))
    norms.append((0.0, 0.0, 1.0))
    # base disc center
    center = len(verts)
    verts.append((0.0, 0.0, zbase))
    uvts.append((0.5, 0.5))
    norms.append((0.0, 0.0, -1.0))

    # side: CCW from outside; one triangle per segment
    for i in range(n):
        j = (i + 1) % n
        faces.append((i, j, apex))
    # base disc: CCW from outside (normal -Z)
    for i in range(n):
        j = (i + 1) % n
        faces.append((center, j, i))

    out = ["# generated by gen_nose_cap.py (unit nose cap: r=%.6g h=%.6g)" % (r, h),
           "o NoseCap"]
    for v in verts:
        out.append("v %.6f %.6f %.6f" % v)
    for t in uvts:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for f in faces:
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            f[0] + 1, f[0] + 1, f[0] + 1, f[1] + 1, f[1] + 1, f[1] + 1,
            f[2] + 1, f[2] + 1, f[2] + 1))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r=%.6g h=%.6g)" %
          (a.dst, len(verts), len(faces), r, h))


if __name__ == "__main__":
    main()
