#!/usr/bin/env python3
"""Generate a tank-adapter .obj mesh: a frustum joining two stack radii.

Part meshes are authored centered at the origin with the stack axis along
+Z. The -Z end carries radius `--r1`, the +Z end radius `--r2`, over the
given `--height`. Convention for the catalog: height = max(r1, r2) / 2,
e.g.

    python3 gen_adapter.py res/adapter_r3to5.obj --r1 3 --r2 5 --height 2.5
    python3 gen_adapter.py res/adapter_r5to3.obj --r1 5 --r2 3 --height 2.5

Geometry: 32 side segments, disc fans on both ends, smooth analytic side
normal, flat normals on the discs. Winding is CCW from outside (the
renderer culls back faces) -- same convention as gen_nose_cap.py. UVs:
the side wraps u around the axis (v = 0 at the -Z rim, 1 at the +Z rim),
the discs are planar -- the part's texture is a flat fill, so they only
need to be present (CalcTangentSpace requires a UV channel).
"""

import argparse
import math


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--r1", type=float, default=1.0,
                    help="radius at the -Z end")
    ap.add_argument("--r2", type=float, default=3.0,
                    help="radius at the +Z end")
    ap.add_argument("--height", type=float, default=1.5,
                    help="frustum height (default: max(r1, r2) / 2)")
    ap.add_argument("--segments", type=int, default=32)
    a = ap.parse_args()
    if a.r1 <= 0 or a.r2 <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("r1/r2/height must be > 0, segments >= 3")

    r1, r2, h, n = a.r1, a.r2, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    # side normal: perpendicular to the (radial, z) side vector
    # (r1, zbase) -> (r2, ztop), pointing out
    L = math.sqrt(h * h + (r2 - r1) * (r2 - r1))

    verts, uvts, norms, faces = [], [], [], []
    # bottom ring (-Z end)
    for i in range(n):
        th = 2.0 * math.pi * i / n
        ct, st = math.cos(th), math.sin(th)
        verts.append((r1 * ct, r1 * st, zbase))
        uvts.append((i / float(n), 0.0))
        norms.append((h * ct / L, h * st / L, (r1 - r2) / L))
    # top ring (+Z end)
    for i in range(n):
        th = 2.0 * math.pi * i / n
        ct, st = math.cos(th), math.sin(th)
        verts.append((r2 * ct, r2 * st, ztop))
        uvts.append((i / float(n), 1.0))
        norms.append((h * ct / L, h * st / L, (r1 - r2) / L))
    # disc centers
    cbase = len(verts)
    verts.append((0.0, 0.0, zbase))
    uvts.append((0.5, 0.5))
    norms.append((0.0, 0.0, -1.0))
    ctop = len(verts)
    verts.append((0.0, 0.0, ztop))
    uvts.append((0.5, 0.5))
    norms.append((0.0, 0.0, 1.0))

    T = n  # top-ring index offset
    # side: CCW from outside; two triangles per segment
    for i in range(n):
        j = (i + 1) % n
        faces.append((i, j, j + T))
        faces.append((i, j + T, i + T))
    # bottom disc: CCW from outside (normal -Z)
    for i in range(n):
        j = (i + 1) % n
        faces.append((cbase, j, i))
    # top disc: CCW from outside (normal +Z); the +T offset is essential --
    # bare i/j index the bottom ring, which would fan the top center onto
    # the smaller ring and leave the top disc missing
    for i in range(n):
        j = (i + 1) % n
        faces.append((ctop, i + T, j + T))

    out = ["# generated by gen_adapter.py (frustum r1=%.6g r2=%.6g h=%.6g)"
           % (r1, r2, h),
           "o Adapter"]
    for v in verts:
        out.append("v %.6f %.6f %.6f" % v)
    for t in uvts:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for f in faces:
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            f[0] + 1, f[0] + 1, f[0] + 1, f[1] + 1, f[1] + 1, f[1] + 1,
            f[2] + 1, f[2] + 1, f[2] + 1))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r1=%.6g r2=%.6g h=%.6g)" %
          (a.dst, len(verts), len(faces), r1, r2, h))


if __name__ == "__main__":
    main()
