TARGET=osp

#CXX_OPT=-march=native -flto -O2 -fprofile-arcs -ftest-coverage -fprofile-dir=/home/dv/src/my/openspaceprogram/data/pgo -fprofile-generate=/home/dv/src/my/openspaceprogram/data/pgo
#LD_OPT=-O2 -flto -fprofile-arcs
#SANITIZE=-g3 -fsanitize=address -fsanitize=leak -fsanitize=undefined

CXX= g++
# -MMD -MP emit a .d dependency file per object so a changed header (e.g. frame.h)
# forces a recompile of every TU that includes it. Without this, make only sees
# the .cpp prerequisite and silently links stale .o files with a mismatched
# struct layout -> heap corruption / segfault. The .d files are -included below.
CXXFLAGS=-O2 -MMD -MP $(CXX_OPT) $(SANITIZE) -Wall -Wextra -Wpedantic -std=c++11 -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/imgui/ -I./middleware/ -I/usr/include/SDL2

LINKER=g++ -O2 $(LD_OPT) $(SANITIZE) -o
LDLIBS=-lSDL2_image -lSDL2 -lGLEW -lGL -lassimp

# imgui submodule (pinned to a tagged release), built like everything else
# (the build rules are near the bottom, after the main target)
IMGUI_DIR=./middleware/imgui
IMGUI_OBJS=./obj/imgui/imgui.o ./obj/imgui/imgui_draw.o ./obj/imgui/imgui_widgets.o ./obj/imgui/imgui_tables.o ./obj/imgui/imgui_impl_sdl2.o ./obj/imgui/imgui_impl_opengl3.o
# clone bullet3 in ./middleware
# cd ./middleware/bullet3
# ln -s bullet src
# build it with cmake with double precision enabled
BULLET3_OBJS=./middleware/bullet3/build/src/BulletDynamics/libBulletDynamics.a ./middleware/bullet3/build/src/BulletCollision/libBulletCollision.a ./middleware/bullet3/build/src/BulletSoftBody/libBulletSoftBody.a ./middleware/bullet3/build/src/Bullet3Geometry/libBullet3Geometry.a ./middleware/bullet3/build/src/BulletInverseDynamics/libBulletInverseDynamics.a ./middleware/bullet3/build/src/Bullet3Common/libBullet3Common.a ./middleware/bullet3/build/src/Bullet3Collision/libBullet3Collision.a ./middleware/bullet3/build/src/LinearMath/libLinearMath.a ./middleware/bullet3/build/src/Bullet3Serialize/Bullet2FileLoader/libBullet2FileLoader.a ./middleware/bullet3/build/src/Bullet3OpenCL/libBullet3OpenCL_clew.a ./middleware/bullet3/build/src/Bullet3Dynamics/libBullet3Dynamics.a

LFLAGS=$(LTO) -Wall $(LDLIBS) $(IMGUI_LIBS) $(BULLET3_OBJS)

SRCDIR=src
OBJDIR=obj
BINDIR=.

SOURCES := $(wildcard $(SRCDIR)/*.cpp)
INCLUDES := $(wildcard $(SRCDIR)/*.h)
OBJECTS  := $(SOURCES:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
# Header dependency files (generated by -MMD). -include is silent when absent
# (first build), and pulls each .o's full include list into the dependency graph.
DEPS     := $(OBJECTS:.o=.d) $(IMGUI_OBJS:.o=.d)
rm = rm -f

$(BINDIR)/$(TARGET): $(OBJECTS) $(IMGUI_OBJS)
	$(LINKER) $@ $(IMGUI_OBJS) $(OBJECTS) $(LFLAGS)

$(OBJECTS): $(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui.o: $(IMGUI_DIR)/imgui.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_draw.o: $(IMGUI_DIR)/imgui_draw.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_widgets.o: $(IMGUI_DIR)/imgui_widgets.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_tables.o: $(IMGUI_DIR)/imgui_tables.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_sdl2.o: $(IMGUI_DIR)/backends/imgui_impl_sdl2.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_opengl3.o: $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Unit tests for the pure-math core (reference frames, orbital math).
# These link against src/frame.cpp directly, so they need no rendering/Bullet.
test:
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_frames.cpp src/frame.cpp -o test_frames
	./test_frames
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_spawn.cpp src/frame.cpp -o test_spawn
	./test_spawn
	# attitude law (pure C, no Bullet): the per-substep braking law
	# main.cpp runs, pinned across the authority/warp grid.
	$(CXX) -O2 -std=c++11 tests/test_attitude.cpp -o test_attitude
	./test_attitude
	# thrust fixes (substep delivery, fuel flow, SetMass inertia): links the
	# real src/physics.cpp, so it pulls in the render chain + Bullet + GL libs.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/ -I/usr/include/SDL2 \
	    tests/test_thrust.cpp src/physics.cpp src/body.cpp src/shader.cpp src/camera.cpp src/mesh.cpp src/texture.cpp src/model.cpp src/gldebug.cpp \
	    $(BULLET3_OBJS) -lGL -lGLEW -lSDL2 -lSDL2_image -lassimp -o test_thrust
	./test_thrust
	# rotation model (physical wheel torque, per-substep law, torque
	# delivery): same real-Bullet link as test_thrust.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/ -I/usr/include/SDL2 \
	    tests/test_rotation.cpp src/physics.cpp src/body.cpp src/shader.cpp src/camera.cpp src/mesh.cpp src/texture.cpp src/model.cpp src/gldebug.cpp \
	    $(BULLET3_OBJS) -lGL -lGLEW -lSDL2 -lSDL2_image -lassimp -o test_rotation
	./test_rotation
	# ship/part JSON data model (GL-free: catalog + ship-def parse/validate,
	# part resolution, aggregates). Runs from the repo root (needs res/).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/ \
	    tests/test_shipload.cpp src/shipdef.cpp -o test_shipload
	./test_shipload
	# fleet JSON (GL-free: entry parse + defaults + error paths).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/ \
	    tests/test_fleet.cpp src/fleet.cpp -o test_fleet
	./test_fleet

# GL-context probe: on this Mesa 26 stack any draw (or vertex-attribute
# setup) made in the default VAO 0 fails with GL_INVALID_OPERATION — draws
# must happen inside a real glGenVertexArrays VAO (even an empty one for a
# vertex-less gl_VertexID quad). Needs an X display:
#     DISPLAY=:99 make test-gl
test-gl:
	$(CXX) -O2 -std=c++11 -I/usr/include/SDL2 tests/test_vertexless.c -lSDL2 -lGLEW -lGL -o test_gl_vao
	./test_gl_vao

.PHONEY: clean
clean:
	$(rm) $(OBJECTS) $(IMGUI_OBJS) $(DEPS)

.PHONEY: remove
remove: clean
	$(rm) $(BINDIR)/$(TARGET) test_frames test_spawn test_attitude test_thrust test_rotation test_shipload test_fleet test_gl_vao

# Pull in the generated header dependencies (see -MMD above). Silent if the
# .d files don't exist yet (fresh checkout / first build).
-include $(DEPS)
