TARGET=osp

#CXX_OPT=-march=native -flto -O2 -fprofile-arcs -ftest-coverage -fprofile-dir=/home/dv/src/my/openspaceprogram/data/pgo -fprofile-generate=/home/dv/src/my/openspaceprogram/data/pgo
#LD_OPT=-O2 -flto -fprofile-arcs
#SANITIZE=-g3 -fsanitize=address -fsanitize=leak -fsanitize=undefined

CXX= g++
# -MMD -MP emit a .d dependency file per object so a changed header (e.g. frame.h)
# forces a recompile of every TU that includes it. Without this, make only sees
# the .cpp prerequisite and silently links stale .o files with a mismatched
# struct layout -> heap corruption / segfault. The .d files are -included below.
CXXFLAGS=-O2 -MMD -MP $(CXX_OPT) $(SANITIZE) -Wall -Wextra -Wpedantic -Wno-unused-variable -Wno-unused-parameter -Wno-unused-but-set-variable -std=c++11 -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/imgui/ -I./middleware/ -I/usr/include/SDL2

LINKER=g++ -O2 $(LD_OPT) $(SANITIZE) -o
LDLIBS=-lSDL2_image -lSDL2 -lGLEW -lGL -lassimp

# Default to all cores: a plain `make` runs parallel (verified: MAKEFLAGS
# set in-file takes effect, and a command-line -jN still overrides it).
# $(shell ...) -- not $(nproc) -- because make 4.4 does not run the shell
# for an undefined variable; it would expand to empty, leaving a bare
# -j, which means *unlimited* jobs.
MAKEFLAGS += -j$(shell nproc)

# imgui submodule (pinned to a tagged release), built like everything else
# (the build rules are near the bottom, after the main target)
IMGUI_DIR=./middleware/imgui
IMGUI_OBJS=./obj/imgui/imgui.o ./obj/imgui/imgui_draw.o ./obj/imgui/imgui_widgets.o ./obj/imgui/imgui_tables.o ./obj/imgui/imgui_impl_sdl2.o ./obj/imgui/imgui_impl_opengl3.o
# implot submodule (pinned to a tagged release): plotting plugin that draws
# through the existing imgui renderer, so only its two .cpp files are built.
IMPLLOT_DIR=./middleware/implot
IMPLLOT_OBJS=./obj/implot/implot.o ./obj/implot/implot_items.o
# clone bullet3 in ./middleware
# cd ./middleware/bullet3
# ln -s bullet src
# build it with cmake with double precision enabled
BULLET3_OBJS=./middleware/bullet3/build/src/BulletDynamics/libBulletDynamics.a ./middleware/bullet3/build/src/BulletCollision/libBulletCollision.a ./middleware/bullet3/build/src/BulletSoftBody/libBulletSoftBody.a ./middleware/bullet3/build/src/Bullet3Geometry/libBullet3Geometry.a ./middleware/bullet3/build/src/BulletInverseDynamics/libBulletInverseDynamics.a ./middleware/bullet3/build/src/Bullet3Common/libBullet3Common.a ./middleware/bullet3/build/src/Bullet3Collision/libBullet3Collision.a ./middleware/bullet3/build/src/LinearMath/libLinearMath.a ./middleware/bullet3/build/src/Bullet3Serialize/Bullet2FileLoader/libBullet2FileLoader.a ./middleware/bullet3/build/src/Bullet3OpenCL/libBullet3OpenCL_clew.a ./middleware/bullet3/build/src/Bullet3Dynamics/libBullet3Dynamics.a

LFLAGS=$(LTO) -Wall $(LDLIBS) $(IMGUI_LIBS) $(BULLET3_OBJS)

SRCDIR=src
OBJDIR=obj
BINDIR=.

SOURCES := $(wildcard $(SRCDIR)/*.cpp)
INCLUDES := $(wildcard $(SRCDIR)/*.h)
OBJECTS  := $(SOURCES:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
# Header dependency files (generated by -MMD). -include is silent when absent
# (first build), and pulls each .o's full include list into the dependency graph.
DEPS     := $(OBJECTS:.o=.d) $(IMGUI_OBJS:.o=.d) $(IMPLLOT_OBJS:.o=.d)
rm = rm -f

$(BINDIR)/$(TARGET): $(OBJECTS) $(IMGUI_OBJS) $(IMPLLOT_OBJS)
	$(LINKER) $@ $(IMGUI_OBJS) $(IMPLLOT_OBJS) $(OBJECTS) $(LFLAGS)

$(OBJECTS): $(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# The git version string into src/version.h (embedded in the main menu by
# gameui.cpp). `version` is phony, so its check re-runs on every build; it
# rewrites the header only when the string actually changed, so a quiet
# `make` stays quiet and gameui.o (which depends on the header file
# itself) is recompiled only when the version changes. A file target with
# no prerequisites (the old form) would be seen as up-to-date forever
# once the header existed, and the menu would keep the stale string.
# Note: make fixes its rebuild plan before recipes run, so a changed
# version lands on the build after the one that rewrote the header;
# `make clean && make` (the release flow) picks it up immediately.
# `make version` re-runs the check on demand (e.g. after adding a tag);
# `make version VERSION=1.0` overrides it outside a git checkout.
.PHONY: version
version:
	@( VERSION_STRING="$(VERSION)"; \
       [ -e "./.git" ] && GITVERSION=$$( git describe --tags --always --dirty --match "[0-9A-Z]*.[0-9A-Z]*" ) && VERSION_STRING=$$GITVERSION ; \
       [ -e "src/version.h" ] && OLDVERSION=$$(grep VERSION src/version.h|cut -d '"' -f2) ; \
       if [ "x$$VERSION_STRING" != "x$$OLDVERSION" ]; then echo "#define VERSION \"$$VERSION_STRING\"" | tee src/version.h ; fi \
     )

src/version.h: version

$(OBJDIR)/gameui.o: src/version.h

./obj/imgui/imgui.o: $(IMGUI_DIR)/imgui.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_draw.o: $(IMGUI_DIR)/imgui_draw.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_widgets.o: $(IMGUI_DIR)/imgui_widgets.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_tables.o: $(IMGUI_DIR)/imgui_tables.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_sdl2.o: $(IMGUI_DIR)/backends/imgui_impl_sdl2.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_opengl3.o: $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/implot/implot.o: $(IMPLLOT_DIR)/implot.cpp
	@mkdir -p ./obj/implot
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/implot/implot_items.o: $(IMPLLOT_DIR)/implot_items.cpp
	@mkdir -p ./obj/implot
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Unit tests for the pure-math core (reference frames, orbital math).
# These link against src/frame.cpp directly, so they need no rendering/Bullet.
test:
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_frames.cpp src/frame.cpp -o test_frames
	./test_frames
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_spawn.cpp src/frame.cpp -o test_spawn
	./test_spawn
	# attitude law (pure C, no Bullet): the per-substep braking law
	# main.cpp runs, pinned across the authority/warp grid.
	$(CXX) -O2 -std=c++11 tests/test_attitude.cpp -o test_attitude
	./test_attitude
	# slew law in 3 DOF (pure C++, no Bullet/GL): the full-transverse law
	# damps the "third-axis" spin the old slew-axis-only law left undamped
	# (the prograde wobble), across spin magnitudes and warps; pins the
	# non-vacuous guard (the old law must wobble) + the authority bound.
	$(CXX) -O2 -std=c++11 tests/test_slew3d.cpp -o test_slew3d
	./test_slew3d
	# thrust fixes (substep delivery, fuel flow, SetMass inertia): links the
	# real src/physics.cpp, so it pulls in the render chain + Bullet + GL libs.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/ -I/usr/include/SDL2 \
	    tests/test_thrust.cpp src/physics.cpp src/body.cpp src/shader.cpp src/camera.cpp src/mesh.cpp src/texture.cpp src/model.cpp src/gldebug.cpp \
	    $(BULLET3_OBJS) -lGL -lGLEW -lSDL2 -lSDL2_image -lassimp -o test_thrust
	./test_thrust
	# fuel drain (the real Vehicle::consumeResourceMass from src/vehicle.h
	# + the real SetMass): pro-rata across the active stage's tanks (not
	# first-tank-first), stage gating, no stranded fuel, no partial drain.
	# Same real-Bullet link as test_thrust (no GL context needed).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/ -I/usr/include/SDL2 \
	    tests/test_fuel.cpp src/physics.cpp src/body.cpp src/shipdef.cpp src/shader.cpp src/camera.cpp src/mesh.cpp src/texture.cpp src/model.cpp src/gldebug.cpp \
	    $(BULLET3_OBJS) -lGL -lGLEW -lSDL2 -lSDL2_image -lassimp -o test_fuel
	./test_fuel
	# rotation model (physical wheel torque, per-substep law, torque
	# delivery): same real-Bullet link as test_thrust.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/ -I/usr/include/SDL2 \
	    tests/test_rotation.cpp src/physics.cpp src/body.cpp src/shader.cpp src/camera.cpp src/mesh.cpp src/texture.cpp src/model.cpp src/gldebug.cpp \
	    $(BULLET3_OBJS) -lGL -lGLEW -lSDL2 -lSDL2_image -lassimp -o test_rotation
	./test_rotation
	# ship/part JSON data model (GL-free: catalog + ship-def parse/validate,
	# part resolution, aggregates). Runs from the repo root (needs res/).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/ \
	    tests/test_shipload.cpp src/shipdef.cpp -o test_shipload
	./test_shipload
	# stage-split bookkeeping (GL-free: which parts/constraints survive vs.
	# drop, and the survivors' links remapped into the compressed indices).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/ \
	    tests/test_stage.cpp src/shipdef.cpp -o test_stage
	./test_stage
	# fleet JSON (GL-free: entry parse + defaults + error paths).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/ \
	    tests/test_fleet.cpp src/fleet.cpp -o test_fleet
	./test_fleet
	# home-planet calendar (src/calendar.h, header-only pure math): day/year
	# from spin/orbit rates, 427-day snapped year, months, epoch year,
	# tidally-locked + star edge cases. Pinned to the Eerbon JSON rates.
	$(CXX) -O2 -std=c++11 -I./src tests/test_calendar.cpp -o test_calendar
	./test_calendar
	# two-body orbital elements + time-to-apsis (src/orbit.h, header-only
	# pure math): elements, anomaly conversions, the ApT/PeT countdown fix,
	# hyperbolic/parabolic handling, degenerate-plane guards.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_orbit.cpp -o test_orbit
	./test_orbit
	# orbit-sampling cache (src/orbitsample.h, header-only pure math): the
	# map's per-orbit points, cached on the elements so coasting orbits are
	# propagated once. Circular/eccentric radii, cache hit + invalidation,
	# hyperbolic -> empty.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_orbitsample.cpp -o test_orbitsample
	./test_orbitsample
	# Lambert solver + min-dv planner (src/transfer.h, header-only pure
	# math): Hohmann analytic reference, round-trip, hyperbolic leg.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_transfer.cpp -o test_transfer
	./test_transfer
	# porkchop 2-D sweep (src/transfer.h, header-only pure math): pinned to
	# planTransfer (t_dep = 0 row) + the Hohmann analytic min + the no-
	# solution (all-NaN) path + grid bookkeeping.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_porkchop.cpp -o test_porkchop
	./test_porkchop
	# surface map projection + terminator (src/surfmap.h, header-only pure
	# math): the equirectangular pixel <-> direction round-trip, the
	# lon/lat convention (lon 0 = +Z, north = +Y -- the same atan2(x, z) /
	# asin(y) render.cpp uses), the shade range, the antimeridian wrap.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_surfmap.cpp -o test_surfmap
	./test_surfmap
	# background job runner (src/job.cpp): the worker/main-thread handoff --
	# the body runs off the calling thread, the returned continuation runs on
	# the poll() thread, jobs land in posted order, a throwing body does not
	# kill the worker, busy()/poll() report the state + the running label.
	$(CXX) -O2 -std=c++11 -I./src tests/test_jobs.cpp src/job.cpp -o test_jobs
	./test_jobs
	# orbital map projection (src/orbitmap.h, pure-math part): project() drops
	# the map normal (+Y) and scales XZ by meters-per-pixel. Header-only, so
	# the imgui include is headers-only (no imgui/Bullet/GL link needed).
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/imgui/ tests/test_orbitmap.cpp -o test_orbitmap
	./test_orbitmap
	# orbit camera (src/camera.cpp, pure math): pitching past the pole must
	# keep the up vector continuous (no sudden roll) and the view NaN-free.
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ tests/test_orbitcam.cpp src/camera.cpp -o test_orbitcam
	./test_orbitcam

# E2E battery: launch the built game under Xvfb and run the pass/fail cases
# in e2e/cases/ (see e2e/run.py). Needs the game binary, so it depends on
# $(TARGET). Runs headless via xvfb-run; on a machine with a real display it
# uses that instead. Stdlib Python only.
# Cases run in parallel (run.py --jobs, default 2); override with JOBS,
# e.g. `make e2e JOBS=4` or `make e2e JOBS=1` for serial.
JOBS ?=
E2E_JOBS = $(if $(JOBS),--jobs $(JOBS),)
.PHONY: e2e
e2e: $(TARGET)
	python3 e2e/run.py $(E2E_JOBS)

# GL-context probe: on this Mesa 26 stack any draw (or vertex-attribute
# setup) made in the default VAO 0 fails with GL_INVALID_OPERATION — draws
# must happen inside a real glGenVertexArrays VAO (even an empty one for a
# vertex-less gl_VertexID quad). Needs an X display:
#     DISPLAY=:99 make test-gl
test-gl:
	$(CXX) -O2 -std=c++11 -I/usr/include/SDL2 tests/test_vertexless.c -lSDL2 -lGLEW -lGL -o test_gl_vao
	./test_gl_vao

.PHONY: clean
clean:
	$(rm) $(OBJECTS) $(OBJECTS:.o=.d)

.PHONY: remove
remove: clean
	$(rm) $(BINDIR)/$(TARGET) test_frames test_spawn test_attitude test_slew3d test_thrust test_fuel test_rotation test_shipload test_stage test_fleet test_calendar test_orbit test_orbitsample test_transfer test_porkchop test_orbitmap test_orbitcam test_surfmap test_jobs test_gl_vao

# Pull in the generated header dependencies (see -MMD above). Silent if the
# .d files don't exist yet (fresh checkout / first build).
-include $(DEPS)
