TARGET=osp

#CXX_OPT=-march=native -flto -O2 -fprofile-arcs -ftest-coverage -fprofile-dir=/home/dv/src/my/openspaceprogram/data/pgo -fprofile-generate=/home/dv/src/my/openspaceprogram/data/pgo
#LD_OPT=-O2 -flto -fprofile-arcs
#SANITIZE=-g3 -fsanitize=address -fsanitize=leak -fsanitize=undefined

CXX= g++
# -MMD -MP emit a .d dependency file per object so a changed header (e.g. frame.h)
# forces a recompile of every TU that includes it. Without this, make only sees
# the .cpp prerequisite and silently links stale .o files with a mismatched
# struct layout -> heap corruption / segfault. The .d files are -included below.
CXXFLAGS=-O2 -MMD -MP $(CXX_OPT) $(SANITIZE) -Wall -Wextra -Wpedantic -std=c++11 -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet -I./middleware/imgui/ -I./middleware/ -I/usr/include/SDL2

LINKER=g++ -O2 $(LD_OPT) $(SANITIZE) -o
LDLIBS=-lSDL2_image -lSDL2 -lGLEW -lGL -lassimp

# imgui submodule (pinned to a tagged release), built like everything else
# (the build rules are near the bottom, after the main target)
IMGUI_DIR=./middleware/imgui
IMGUI_OBJS=./obj/imgui/imgui.o ./obj/imgui/imgui_draw.o ./obj/imgui/imgui_widgets.o ./obj/imgui/imgui_tables.o ./obj/imgui/imgui_impl_sdl2.o ./obj/imgui/imgui_impl_opengl3.o
# clone bullet3 in ./middleware
# cd ./middleware/bullet3
# ln -s bullet src
# build it with cmake with double precision enabled
BULLET3_OBJS=./middleware/bullet3/build/src/BulletDynamics/libBulletDynamics.a ./middleware/bullet3/build/src/BulletCollision/libBulletCollision.a ./middleware/bullet3/build/src/BulletSoftBody/libBulletSoftBody.a ./middleware/bullet3/build/src/Bullet3Geometry/libBullet3Geometry.a ./middleware/bullet3/build/src/BulletInverseDynamics/libBulletInverseDynamics.a ./middleware/bullet3/build/src/Bullet3Common/libBullet3Common.a ./middleware/bullet3/build/src/Bullet3Collision/libBullet3Collision.a ./middleware/bullet3/build/src/LinearMath/libLinearMath.a ./middleware/bullet3/build/src/Bullet3Serialize/Bullet2FileLoader/libBullet2FileLoader.a ./middleware/bullet3/build/src/Bullet3OpenCL/libBullet3OpenCL_clew.a ./middleware/bullet3/build/src/Bullet3Dynamics/libBullet3Dynamics.a

LFLAGS=$(LTO) -Wall $(LDLIBS) $(IMGUI_LIBS) $(BULLET3_OBJS)

SRCDIR=src
OBJDIR=obj
BINDIR=.

SOURCES := $(wildcard $(SRCDIR)/*.cpp)
INCLUDES := $(wildcard $(SRCDIR)/*.h)
OBJECTS  := $(SOURCES:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
# Header dependency files (generated by -MMD). -include is silent when absent
# (first build), and pulls each .o's full include list into the dependency graph.
DEPS     := $(OBJECTS:.o=.d) $(IMGUI_OBJS:.o=.d)
rm = rm -f

$(BINDIR)/$(TARGET): $(OBJECTS) $(IMGUI_OBJS)
	$(LINKER) $@ $(IMGUI_OBJS) $(OBJECTS) $(LFLAGS)

$(OBJECTS): $(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui.o: $(IMGUI_DIR)/imgui.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_draw.o: $(IMGUI_DIR)/imgui_draw.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_widgets.o: $(IMGUI_DIR)/imgui_widgets.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_tables.o: $(IMGUI_DIR)/imgui_tables.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_sdl2.o: $(IMGUI_DIR)/backends/imgui_impl_sdl2.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

./obj/imgui/imgui_impl_opengl3.o: $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp
	@mkdir -p ./obj/imgui
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Unit tests for the pure-math core (reference frames, orbital math).
# These link against src/frame.cpp directly, so they need no rendering/Bullet.
test:
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_frames.cpp src/frame.cpp -o test_frames
	./test_frames
	$(CXX) -O2 -std=c++11 -I./src -I./middleware/glm/ -I./middleware/bullet3/ -I./middleware/bullet3/bullet \
	    tests/test_spawn.cpp src/frame.cpp -o test_spawn
	./test_spawn

.PHONEY: clean
clean:
	$(rm) $(OBJECTS) $(IMGUI_OBJS) $(DEPS)

.PHONEY: remove
remove: clean
	$(rm) $(BINDIR)/$(TARGET) test_frames test_spawn

# Pull in the generated header dependencies (see -MMD above). Silent if the
# .d files don't exist yet (fresh checkout / first build).
-include $(DEPS)
