#!/usr/bin/env python3
"""Generate a wing .obj: triangular delta plate (chord X, span +Z, thickness Y).
Shared verts + smooth normals keep the mesh watertight (for volume/mass); CCW winding."""

import argparse
import math


def cross(a, b):
    return (a[1]*b[2] - a[2]*b[1],
            a[2]*b[0] - a[0]*b[2],
            a[0]*b[1] - a[1]*b[0])


def sub(a, b):
    return (a[0]-b[0], a[1]-b[1], a[2]-b[2])


def norm(v):
    L = math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])
    if L == 0.0:
        return (0.0, 0.0, 0.0)
    return (v[0]/L, v[1]/L, v[2]/L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--span", type=float, default=2.0,
                    help="root-to-tip span along +Z (default 2.0)")
    ap.add_argument("--chord", type=float, default=2.0,
                    help="root chord along X (default 2.0)")
    ap.add_argument("--thickness", type=float, default=0.1,
                    help="plate thickness along Y (default 0.1)")
    a = ap.parse_args()
    if a.span <= 0 or a.chord <= 0 or a.thickness <= 0:
        ap.error("span/chord/thickness must be > 0")

    hc = a.chord / 2.0
    ht = a.thickness / 2.0
    rz = -a.span / 2.0
    tz = +a.span / 2.0

    # triangular prism: root-LE/root-TE at rz, tip at tz, extruded +-ht in Y
    A_t = (-hc,  ht, rz)   # 0  root leading edge, top
    B_t = ( hc,  ht, rz)   # 1  root trailing edge, top
    C_t = ( 0.0, ht, tz)   # 2  tip, top
    A_b = (-hc, -ht, rz)   # 3  root leading edge, bottom
    B_b = ( hc, -ht, rz)   # 4  root trailing edge, bottom
    C_b = ( 0.0, -ht, tz)  # 5  tip, bottom
    corners = [A_t, B_t, C_t, A_b, B_b, C_b]

    # 8 triangles: 2 triangular caps + 3 rectangular sides (each split in two)
    face_idx = [
        (0, 2, 1),   # top cap (+Y)
        (3, 4, 5),   # bottom cap (-Y)
        (0, 3, 4),   # root chord side, tri 1
        (0, 4, 1),   # root chord side, tri 2
        (0, 2, 5),   # root-LE -> tip side, tri 1
        (0, 5, 3),   # root-LE -> tip side, tri 2
        (1, 4, 5),   # root-TE -> tip side, tri 1
        (1, 5, 2),   # root-TE -> tip side, tri 2
    ]

    # shared corners + smooth normals: keeps the mesh watertight so mesh_geom
    # reads true volume (not the bounding-cylinder fallback)
    acc = [[0.0, 0.0, 0.0] for _ in corners]
    faces = []
    for (i0, i1, i2) in face_idx:
        p0, p1, p2 = corners[i0], corners[i1], corners[i2]
        n = norm(cross(sub(p1, p0), sub(p2, p0)))
        c = ((p0[0]+p1[0]+p2[0])/3.0, (p0[1]+p1[1]+p2[1])/3.0,
             (p0[2]+p1[2]+p2[2])/3.0)
        if (n[0]*c[0] + n[1]*c[1] + n[2]*c[2]) < 0.0:
            i1, i2 = i2, i1                  # flip winding -> CCW from outside
            n = (-n[0], -n[1], -n[2])
        faces.append((i0, i1, i2))
        for k in (i0, i1, i2):
            acc[k][0] += n[0]
            acc[k][1] += n[1]
            acc[k][2] += n[2]
    vertex_normals = [norm(t) for t in acc]

    out = ["# generated by gen_wing.py (delta wing: chord=%.6g span=%.6g t=%.6g)"
           % (a.chord, a.span, a.thickness), "o Wing"]
    for v in corners:
        out.append("v %.6f %.6f %.6f" % v)
    for _ in corners:                      # flat-fill texture: UVs only exist
        out.append("vt 0.000000 0.000000")
    for v in vertex_normals:
        out.append("vn %.6f %.6f %.6f" % v)
    for (i0, i1, i2) in faces:
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            i0 + 1, i0 + 1, i0 + 1, i1 + 1, i1 + 1, i1 + 1, i2 + 1, i2 + 1, i2 + 1))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d corners, %d faces (chord=%.6g span=%.6g t=%.6g)" %
          (a.dst, len(corners), len(face_idx), a.chord, a.span, a.thickness))


if __name__ == "__main__":
    main()
