#!/usr/bin/env python3
"""Generate a wing .obj mesh: a triangular (delta) plate.

Part meshes are authored centered at the origin. The wing is a delta in the
stack frame: the root chord (default 2 m) lies along X at the root, the tip
is a point 2 m outboard along the stack axis (+Z), and it is a constant
thickness (default 0.1 m) along Y. The planform is a triangle -- the 2 m root
chord (X, at z = -1) tapering to the tip (x = 0, z = +1) -- so its two "sides"
are 2 m x 2 m. It is a convex triangular prism, so its mesh doubles as its
collision hull (see PhysicsEngine::BuildHull).

Winding is CCW from outside (the renderer culls back faces). The six corners
are shared vertices with SMOOTH per-vertex normals (each the average of its
adjacent face normals): sharing vertices keeps the mesh watertight, so
gen_parts.py's mesh_geom reads the true enclosed volume (not its
bounding-cylinder fallback) and the wing's mass stays a sane function of its
size. UVs are present (CalcTangentSpace wants a UV channel) but the part's
texture is a flat fill, so they only need to exist.

    python3 gen_wing.py res/wing.obj
"""

import argparse
import math


def cross(a, b):
    return (a[1]*b[2] - a[2]*b[1],
            a[2]*b[0] - a[0]*b[2],
            a[0]*b[1] - a[1]*b[0])


def sub(a, b):
    return (a[0]-b[0], a[1]-b[1], a[2]-b[2])


def norm(v):
    L = math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])
    if L == 0.0:
        return (0.0, 0.0, 0.0)
    return (v[0]/L, v[1]/L, v[2]/L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--span", type=float, default=2.0,
                    help="root-to-tip span along +Z (default 2.0)")
    ap.add_argument("--chord", type=float, default=2.0,
                    help="root chord along X (default 2.0)")
    ap.add_argument("--thickness", type=float, default=0.1,
                    help="plate thickness along Y (default 0.1)")
    a = ap.parse_args()
    if a.span <= 0 or a.chord <= 0 or a.thickness <= 0:
        ap.error("span/chord/thickness must be > 0")

    hc = a.chord / 2.0        # root half-chord (X)
    ht = a.thickness / 2.0    # half thickness (Y)
    rz = -a.span / 2.0        # root z (at the fuselage)
    tz = +a.span / 2.0        # tip z (outboard)

    # The six corners of the triangular prism. The planform triangle is
    # root-LE (-hc, rz), root-TE (+hc, rz), tip (0, tz); extruded +-ht in Y.
    A_t = (-hc,  ht, rz)   # 0  root leading edge, top
    B_t = ( hc,  ht, rz)   # 1  root trailing edge, top
    C_t = ( 0.0, ht, tz)   # 2  tip, top
    A_b = (-hc, -ht, rz)   # 3  root leading edge, bottom
    B_b = ( hc, -ht, rz)   # 4  root trailing edge, bottom
    C_b = ( 0.0, -ht, tz)  # 5  tip, bottom
    corners = [A_t, B_t, C_t, A_b, B_b, C_b]

    # Eight triangles: the two triangular caps (top/bottom) plus the three
    # rectangular sides (each split into two). The prism is convex and
    # centered at the origin, so a face's outward normal points away from
    # the origin -- I orient each face (and its winding) to agree.
    face_idx = [
        (0, 2, 1),   # top cap (+Y)
        (3, 4, 5),   # bottom cap (-Y)
        (0, 3, 4),   # root chord side, tri 1
        (0, 4, 1),   # root chord side, tri 2
        (0, 2, 5),   # root-LE -> tip side, tri 1
        (0, 5, 3),   # root-LE -> tip side, tri 2
        (1, 4, 5),   # root-TE -> tip side, tri 1
        (1, 5, 2),   # root-TE -> tip side, tri 2
    ]

    # The six corners are SHARED (one vertex each, not duplicated per face)
    # and carry SMOOTH normals (the average of their adjacent face normals).
    # Sharing vertices keeps the mesh watertight, so gen_parts.py's mesh_geom
    # reads the true enclosed volume (not its bounding-cylinder fallback) and
    # the wing's mass stays a sane function of its size. Each face is oriented
    # CCW-from-outside (the renderer culls back faces) by flipping its winding
    # when its geometric normal points toward the prism's centroid.
    acc = [[0.0, 0.0, 0.0] for _ in corners]
    faces = []
    for (i0, i1, i2) in face_idx:
        p0, p1, p2 = corners[i0], corners[i1], corners[i2]
        n = norm(cross(sub(p1, p0), sub(p2, p0)))
        c = ((p0[0]+p1[0]+p2[0])/3.0, (p0[1]+p1[1]+p2[1])/3.0,
             (p0[2]+p1[2]+p2[2])/3.0)
        if (n[0]*c[0] + n[1]*c[1] + n[2]*c[2]) < 0.0:
            i1, i2 = i2, i1                  # flip winding -> CCW from outside
            n = (-n[0], -n[1], -n[2])
        faces.append((i0, i1, i2))
        for k in (i0, i1, i2):
            acc[k][0] += n[0]
            acc[k][1] += n[1]
            acc[k][2] += n[2]
    vertex_normals = [norm(t) for t in acc]

    out = ["# generated by gen_wing.py (delta wing: chord=%.6g span=%.6g t=%.6g)"
           % (a.chord, a.span, a.thickness), "o Wing"]
    for v in corners:
        out.append("v %.6f %.6f %.6f" % v)
    for _ in corners:                      # flat-fill texture: UVs only exist
        out.append("vt 0.000000 0.000000")
    for v in vertex_normals:
        out.append("vn %.6f %.6f %.6f" % v)
    for (i0, i1, i2) in faces:
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            i0 + 1, i0 + 1, i0 + 1, i1 + 1, i1 + 1, i1 + 1, i2 + 1, i2 + 1, i2 + 1))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d corners, %d faces (chord=%.6g span=%.6g t=%.6g)" %
          (a.dst, len(corners), len(face_idx), a.chord, a.span, a.thickness))


if __name__ == "__main__":
    main()
