#!/usr/bin/env python3
"""Generate a nose-cap .obj: pointy cone (stack axis +Z). Flat per-face normals; CCW winding.
Larger caps are uniform rescales (sz = r, not rescale_obj's usual h/2)."""

import argparse
import math


def unit(v):
    L = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    return (v[0] / L, v[1] / L, v[2] / L)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def face_normal(a, b, c):
    return unit(cross((b[0] - a[0], b[1] - a[1], b[2] - a[2]),
                      (c[0] - a[0], c[1] - a[1], c[2] - a[2])))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--radius", type=float, default=1.0)
    ap.add_argument("--height", type=float, default=0.5,
                    help="cone height (default: radius / 2)")
    ap.add_argument("--segments", type=int, default=32)
    a = ap.parse_args()
    if a.radius <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("radius/height must be > 0, segments >= 3")

    r, h, n = a.radius, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    # shared positions: base ring, apex, disc center
    pos = []
    for i in range(n):
        th = 2.0 * math.pi * i / n
        pos.append((r * math.cos(th), r * math.sin(th), zbase))
    apex = len(pos); pos.append((0.0, 0.0, ztop))
    center = len(pos); pos.append((0.0, 0.0, zbase))

    uv = [(i / float(n), 0.0) for i in range(n)] + [(0.0, 1.0), (0.5, 0.5)]

    faces = []
    for i in range(n):
        j = (i + 1) % n
        faces.append((i, j, apex))
        faces.append((center, j, i))

    # one normal per face keeps the facets hard-edged through assimp
    norms = [face_normal(pos[i], pos[j], pos[k]) for (i, j, k) in faces]

    out = ["# generated by gen_nose_cap.py (unit nose cap: r=%.6g h=%.6g, flat)" % (r, h),
           "o NoseCap"]
    for p in pos:
        out.append("v %.6f %.6f %.6f" % p)
    for t in uv:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for fidx, (i, j, k) in enumerate(faces):
        fvn = fidx + 1
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            i + 1, i + 1, fvn,
            j + 1, j + 1, fvn,
            k + 1, k + 1, fvn))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r=%.6g h=%.6g, flat)" %
          (a.dst, len(pos), len(faces), r, h))


if __name__ == "__main__":
    main()
