#!/usr/bin/env python3
"""Generate an engine-shroud .obj: open cylinder (no caps), axis +Z, CCW winding.
Flat per-face normals; author at 0.98x engine radius to avoid z-fighting."""

import argparse
import math


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--radius", type=float, default=0.98)
    ap.add_argument("--height", type=float, default=2.0)
    ap.add_argument("--segments", type=int, default=32,
                    help="cylinder side segments (default: 32, like the engines)")
    a = ap.parse_args()
    if a.radius <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("radius/height must be > 0, segments >= 3")

    r, h, n = a.radius, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    cols = []
    for i in range(n):
        th = 2.0 * math.pi * i / n
        cols.append((r * math.cos(th), r * math.sin(th)))

    uvts = [(i / float(n), 0.0) for i in range(n)]

    # one normal per face keeps the facets hard-edged through assimp
    norms = []
    for i in range(n):
        th = 2.0 * math.pi * (i + 0.5) / n
        norms.append((math.cos(th), math.sin(th), 0.0))

    def vidx(col, ring):
        return col + (ring * n) + 1

    def fline(c0, c1, c2, fvn):
        (a0, r0), (a1, r1), (a2, r2) = c0, c1, c2
        return "f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            vidx(a0, r0), a0 + 1, fvn,
            vidx(a1, r1), a1 + 1, fvn,
            vidx(a2, r2), a2 + 1, fvn)

    out = ["# generated by gen_engine_shroud.py (open cylinder: r=%.6g h=%.6g, %d segs, flat)"
           % (r, h, n),
           "o EngineShroud"]
    for i in range(n):
        out.append("v %.6f %.6f %.6f" % (cols[i][0], cols[i][1], zbase))
    for i in range(n):
        out.append("v %.6f %.6f %.6f" % (cols[i][0], cols[i][1], ztop))
    for t in uvts:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for i in range(n):
        j = (i + 1) % n
        fvn = i + 1
        # two triangles per segment, CCW from outside; each references the face normal
        out.append(fline((i, 0), (j, 0), (j, 1), fvn))
        out.append(fline((i, 0), (j, 1), (i, 1), fvn))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r=%.6g h=%.6g)" %
          (a.dst, 2 * n, 2 * n, r, h))


if __name__ == "__main__":
    main()
