#!/usr/bin/env python3
"""Generate an engine-shroud .obj mesh: an OPEN cylinder (no caps) that
wraps an engine part. The game draws it over an engine when a part is
attached on the engine's exhaust face (a child below), hiding the nozzle
and cowl in a plain light-gray cylinder (src/vehicle.cpp Vehicle::Draw,
src/render.cpp drawVab).

Part meshes are authored centered at the origin with the stack axis along
+Z, so the shroud is z in [-h/2, +h/2]. Author it slightly INSIDE the
engine's radius (0.98 x), so its rim never sits on the engine's top disc
edge or on a part stacked above (no z-fighting).

Flat shading: every face carries its OWN normal (per-face vn, referenced
by all three of its corners), so assimp's JoinIdenticalVertices keeps the
facets hard-edged -- the Blender "flat" look the smooth engine mesh does
not have. Winding is CCW from outside (the renderer culls back faces).
UVs wrap u around the axis, v along the height: the shroud texture is a
flat fill, so they only need to be present (CalcTangentSpace requires a
UV channel).

    python3 gen_engine_shroud.py res/engine_shroud.obj --radius 0.98 --height 2
"""

import argparse
import math


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--radius", type=float, default=0.98)
    ap.add_argument("--height", type=float, default=2.0)
    ap.add_argument("--segments", type=int, default=32,
                    help="cylinder side segments (default: 32, like the engines)")
    a = ap.parse_args()
    if a.radius <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("radius/height must be > 0, segments >= 3")

    r, h, n = a.radius, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    # one position per column, on each ring (shared, smooth positions)
    cols = []
    for i in range(n):
        th = 2.0 * math.pi * i / n
        cols.append((r * math.cos(th), r * math.sin(th)))

    # one UV per column (u wraps around, v = 0 at the base rim, 1 at the top)
    uvts = [(i / float(n), 0.0) for i in range(n)]

    # one normal PER FACE (the flat-shading trick): radial at the segment
    # midpoint. A corner referenced with two faces' normals stays a
    # distinct vertex through assimp's JoinIdenticalVertices, so the
    # facets render hard-edged.
    norms = []
    for i in range(n):
        th = 2.0 * math.pi * (i + 0.5) / n
        norms.append((math.cos(th), math.sin(th), 0.0))

    def vidx(col, ring):
        # corners (col, ring) -> 1-based v index: bottom ring first
        return col + (ring * n) + 1

    def fline(c0, c1, c2, fvn):
        (a0, r0), (a1, r1), (a2, r2) = c0, c1, c2
        return "f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            vidx(a0, r0), a0 + 1, fvn,
            vidx(a1, r1), a1 + 1, fvn,
            vidx(a2, r2), a2 + 1, fvn)

    out = ["# generated by gen_engine_shroud.py (open cylinder: r=%.6g h=%.6g, %d segs, flat)"
           % (r, h, n),
           "o EngineShroud"]
    for i in range(n):
        out.append("v %.6f %.6f %.6f" % (cols[i][0], cols[i][1], zbase))
    for i in range(n):
        out.append("v %.6f %.6f %.6f" % (cols[i][0], cols[i][1], ztop))
    for t in uvts:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for i in range(n):
        j = (i + 1) % n
        fvn = i + 1   # 1-based face-normal index (one normal per segment)
        # two triangles per segment, CCW from outside (the (b_i, b_j, t_j)
        # normal points out of the segment's midpoint); all three corners
        # of each triangle reference the FACE normal -> flat shading
        out.append(fline((i, 0), (j, 0), (j, 1), fvn))
        out.append(fline((i, 0), (j, 1), (i, 1), fvn))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r=%.6g h=%.6g)" %
          (a.dst, 2 * n, 2 * n, r, h))


if __name__ == "__main__":
    main()
