#!/usr/bin/env python3
"""Generate the radial-decoupler .obj: 0.1x0.1x0.5 block (attach axis +Z).
Flat normals; CCW winding (asserted)."""

import argparse


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--width", type=float, default=0.1, help="x span")
    ap.add_argument("--depth", type=float, default=0.1, help="y span")
    ap.add_argument("--length", type=float, default=0.5,
                    help="z span (the attach axis)")
    a = ap.parse_args()
    if min(a.width, a.depth, a.length) <= 0:
        ap.error("width/depth/length must be > 0")

    w, d, l = a.width, a.depth, a.length
    x, y, z = w / 2.0, d / 2.0, l / 2.0

    # corners (x, y, z)
    A = (-x, -y, -z); B = (x, -y, -z); C = (x, y, -z); D = (-x, y, -z)
    E = (-x, -y, z);  F = (x, -y, z);  G = (x, y, z);  H = (-x, y, z)

    faces = [
        ((-1, 0, 0), [(A, H, D), (A, E, H)]),
        ((1, 0, 0),  [(B, C, G), (B, G, F)]),
        ((0, -1, 0), [(A, B, F), (A, F, E)]),
        ((0, 1, 0),  [(D, H, C), (C, H, G)]),
        ((0, 0, -1), [(A, C, B), (A, D, C)]),
        ((0, 0, 1),  [(E, F, G), (E, G, H)]),
    ]

    def cross(u, v):
        return (u[1]*v[2] - u[2]*v[1],
                u[2]*v[0] - u[0]*v[2],
                u[0]*v[1] - u[1]*v[0])
    for n, tris in faces:
        for t in tris:
            c = cross((t[1][0]-t[0][0], t[1][1]-t[0][1], t[1][2]-t[0][2]),
                      (t[2][0]-t[0][0], t[2][1]-t[0][1], t[2][2]-t[0][2]))
            dot = c[0]*n[0] + c[1]*n[1] + c[2]*n[2]
            if dot <= 0:
                raise SystemExit("winding error: face %s triangle %s" % (n, t))

    uv_axes = {(-1, 0, 0): (1, 2), (1, 0, 0): (1, 2),
               (0, -1, 0): (0, 2), (0, 1, 0): (0, 2),
               (0, 0, -1): (0, 1), (0, 0, 1): (0, 1)}

    def uv_of(pt, n):
        ui, vi = uv_axes[n]
        span_u = (x if ui == 0 else y if ui == 1 else z)
        span_v = (x if vi == 0 else y if vi == 1 else z)
        return (pt[ui] / span_u + 1.0) / 2.0, (pt[vi] / span_v + 1.0) / 2.0

    verts, uvts, norms, faces_out = [], [], [], []
    for n, tris in faces:
        for t in tris:
            for pt in t:
                verts.append(pt)
                uvts.append(uv_of(pt, n))
                norms.append(n)
                faces_out.append(len(verts) - 1)

    out = ["# generated by gen_decoupler_radial.py (radial decoupler: %.6g x %.6g x %.6g)" % (w, d, l),
           "o DecouplerRadial"]
    for v in verts:
        out.append("v %.6f %.6f %.6f" % v)
    for t in uvts:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for i in range(0, len(faces_out), 3):
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            faces_out[i] + 1, faces_out[i] + 1, faces_out[i] + 1,
            faces_out[i+1] + 1, faces_out[i+1] + 1, faces_out[i+1] + 1,
            faces_out[i+2] + 1, faces_out[i+2] + 1, faces_out[i+2] + 1))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (%.6g x %.6g x %.6g)" %
          (a.dst, len(verts), len(faces_out) // 3, w, d, l))


if __name__ == "__main__":
    main()
