#!/usr/bin/env python3
"""Generate a nose-cap .obj mesh: a simple pointy cone (stack axis +Z).

Part meshes are authored centered at the origin with the stack axis along
+Z. The unit cap is radius 1, height 0.5 (height = radius / 2): a base
disc at z = -h/2 and an apex at z = +h/2. The larger caps keep the same
shape, so they are UNIFORM rescales of the unit cap by their radius r
(sx = sy = sz = r):

    python3 gen_nose_cap.py res/nose_cap.obj
    python3 rescale_obj.py res/nose_cap.obj res/nose_cap_r1.5h0.75.obj --sx 1.5 --sy 1.5 --sz 1.5
    python3 rescale_obj.py res/nose_cap.obj res/nose_cap_r2.25h1.125.obj --sx 2.25 --sy 2.25 --sz 2.25

(sz differs from rescale_obj.py's usual sz = h/2, which assumes a 2 m-tall
base cube; this cap's base is only 0.5 m tall, so the correct z scale is
h / 0.5 = 2h = r -- a uniform scale that keeps the cone's angle.)

Flat shading: every face carries its OWN normal (per-face vn, referenced by
all three of its corners), so assimp's JoinIdenticalVertices keeps the
facets hard-edged -- the Blender "flat" look the smooth analytic normals
did not give. Winding is CCW from outside (the renderer culls back faces).
UVs: the side wraps u around the axis (v = 0 at the base rim, 1 at the
apex), the disc is planar -- the part's texture is a flat fill, so they
only need to be present (CalcTangentSpace requires a UV channel).
"""

import argparse
import math


def unit(v):
    L = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    return (v[0] / L, v[1] / L, v[2] / L)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def face_normal(a, b, c):
    # CCW (from outside) triangle -> outward normal
    return unit(cross((b[0] - a[0], b[1] - a[1], b[2] - a[2]),
                      (c[0] - a[0], c[1] - a[1], c[2] - a[2])))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dst", help="destination .obj")
    ap.add_argument("--radius", type=float, default=1.0)
    ap.add_argument("--height", type=float, default=0.5,
                    help="cone height (default: radius / 2)")
    ap.add_argument("--segments", type=int, default=32)
    a = ap.parse_args()
    if a.radius <= 0 or a.height <= 0 or a.segments < 3:
        ap.error("radius/height must be > 0, segments >= 3")

    r, h, n = a.radius, a.height, a.segments
    zbase, ztop = -h / 2.0, h / 2.0

    # shared positions: the base ring, then the apex, then the disc center
    pos = []
    for i in range(n):
        th = 2.0 * math.pi * i / n
        pos.append((r * math.cos(th), r * math.sin(th), zbase))
    apex = len(pos); pos.append((0.0, 0.0, ztop))
    center = len(pos); pos.append((0.0, 0.0, zbase))

    # UVs in the same order as the positions (side ring, apex, disc center)
    uv = [(i / float(n), 0.0) for i in range(n)] + [(0.0, 1.0), (0.5, 0.5)]

    # faces (0-based into pos): the side triangles, then the base disc fan
    faces = []
    for i in range(n):
        j = (i + 1) % n
        faces.append((i, j, apex))        # side, CCW from outside
        faces.append((center, j, i))      # base disc, CCW from outside (normal -Z)

    # one normal PER FACE (the flat-shading trick): each triangle's own
    # outward normal. A corner referenced with two faces' normals stays a
    # distinct vertex through assimp's JoinIdenticalVertices, so the facets
    # render hard-edged.
    norms = [face_normal(pos[i], pos[j], pos[k]) for (i, j, k) in faces]

    out = ["# generated by gen_nose_cap.py (unit nose cap: r=%.6g h=%.6g, flat)" % (r, h),
           "o NoseCap"]
    for p in pos:
        out.append("v %.6f %.6f %.6f" % p)
    for t in uv:
        out.append("vt %.6f %.6f" % t)
    for v in norms:
        out.append("vn %.6f %.6f %.6f" % v)
    for fidx, (i, j, k) in enumerate(faces):
        fvn = fidx + 1   # 1-based face-normal index (one normal per face)
        out.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (
            i + 1, i + 1, fvn,
            j + 1, j + 1, fvn,
            k + 1, k + 1, fvn))
    out.append("")

    with open(a.dst, "w") as f:
        f.write("\n".join(out))
    print("%s: %d verts, %d faces (r=%.6g h=%.6g, flat)" %
          (a.dst, len(pos), len(faces), r, h))


if __name__ == "__main__":
    main()
